### ISSUE TITLE
Завести автодеплой на сервер Веб-стандартов

### ISSUE THREAD

**Issue by pepelsbey** [web-standards-ru/weblind.ru#14]
Мы договорились перевезти сайт на сервер Веб-стандартов, чтобы завести HTTPS, автосборку Тревисом из мастера и вот это всё. Я наобещал, а тебе, @h4, теперь отдуваться :) Поможешь?

Как будет готово (по обычному пути, как и у других сайтов, можно пока коннектиться по ssh к `web-standards.ru`, наверное) — я уже сам настрою домен в nginx, перенесём NS и уже после посмотрим, как оно деплоится на живой.

**Comment by h4** [comment]
@pepelsbey А можешь dev.weblind.ru завести и на сервак нацелить?

**Comment by pepelsbey** [comment]
У меня пока нет доступа к `weblind.ru`, я предлагаю сначала просто завести `rsync` в папку, проверить, что там всё на месте и уже потом туда перенапраить домен.

**Comment by h4** [comment]
@pepelsbey зайди сюда https://travis-ci.org/profile/web-standards-ru?offset=0 и включи интеграцию, пожалуйста.

**Comment by pepelsbey** [comment]
@h4 готово!
