### ISSUE TITLE
Сделать сборку JS

### ISSUE THREAD

**Issue by pepelsbey** [web-standards-ru/weblind.ru#15]
Сейчас три файла просто копируются, надо их наверное изуродовать и склеить. Но хочется, чтобы сайт продолжал просто работать из `src/index.html` без сервера и сборки. А сборка всё просто улучшала. То есть нужно будет делать автозамены в HTML.

**Comment by arslan-akh** [comment]
Стоит ли таскать jquery и inner.js на index.html? Может только на inner.html склеить inner.js и jquery? В итоге получится например:
1. index.js(изуродованный)
2. inner.js(изуродованный и склеен с jquery)

**Comment by pepelsbey** [comment]
Да, хорошая идея — так сейчас и подключается.

**Comment by arslan-akh** [comment]
Готово :)
#18

**Comment by arslan-akh** [comment]
Наверное можно закрывать issue?)

**Comment by pepelsbey** [comment]
Fixed in #18
