### ISSUE TITLE
Склеить CSS

### ISSUE THREAD

**Issue by pepelsbey** [web-standards-ru/weblind.ru#16]
Сейчас все файлы просто минифицируются, надо их склеить. Но хочется, чтобы сайт продолжал просто работать из `src/index.html` без сервера и сборки. А сборка всё просто улучшала. То есть нужно будет делать автозамены в HTML, наверное.

**Comment by arslan-akh** [comment]
Добрый день, если все верно понял, то вот #17

**Comment by pepelsbey** [comment]
Сделано в #17
