### ISSUE TITLE
Оптимизировать подключение JS

### ISSUE THREAD

**Issue by pepelsbey** [web-standards-ru/weblind.ru#19]
Видимо, поставить в конец документа с `defer`. Подумать, подходит ли такая модель — вроде да. Ничего критичного в скриптах нет, только красота.

**Comment by nikolai-shabalin** [comment]
Если в конец страницы добавить, то и от `DOMContentLoaded` в скритах можно отказаться, так как он уже произошёл.
Из-за этого проще можно разделить `inner.js` на "компоненты"  -`menu.js`, `scroll.js`.
И бандлеры не понадобятся.

**Comment by nikolai-shabalin** [comment]
PR #53

**Comment by pepelsbey** [comment]
Исправлено в #53
