### ISSUE TITLE
Отложить загрузку Ютуба до клика

### ISSUE THREAD

**Issue by pepelsbey** [web-standards-ru/weblind.ru#20]
Иначе сейчас на внутренюю страницу приезжает полметра JS от Ютуба для иллюстративного видео. Можно сделать по примеру WSD: [HTML](https://github.com/web-standards-ru/web-standards-days/blob/master/src/pages/index.html#L450-L458), [CSS](https://github.com/web-standards-ru/web-standards-days/blob/master/src/styles/blocks/video.scss), [JS](https://github.com/web-standards-ru/web-standards-days/blob/master/src/scripts/script.js#L122-L171).

**Comment by olegbilyk** [comment]
Сегодня добавлю решение по примеру WSD

**Comment by h4** [comment]
@olegbilyk к сожалению, github не умеет читать по-русски, и в коммите лучше писать `Closes #20` (именно так, без Issues). Строчку про Fixes/Closes лучше вставлять в тело коммит-мессаджа, а не в заголовок.
