### ISSUE TITLE
Оптимизировать стили

### ISSUE THREAD

**Issue by tsergeytovarov** [web-standards-ru/weblind.ru#24]
Склеить их в один файл, сжать. Сделать это средствами сборки наверное. Добавить автопрефиксер.

**Comment by pepelsbey** [comment]
[Уже, просто не задеплоено](https://github.com/web-standards-ru/weblind.ru/blob/master/gulpfile.js#L21-L28). Смотри на репозиторий, живой сайт пока отстаёт.
