### ISSUE TITLE
Избавиться от тега style

### ISSUE THREAD

**Issue by tsergeytovarov** [web-standards-ru/weblind.ru#26]

**Comment by pepelsbey** [comment]
Уточни? Я не вижу ничего такого в коде.

**Comment by tsergeytovarov** [comment]
```

**Comment by tsergeytovarov** [comment]
Скорее всего некоторые из них ставятся через JS, но остальные мне кажется можно убрать в CSS

**Comment by tsergeytovarov** [comment]
https://github.com/web-standards-ru/weblind.ru/blob/master/src/inner.html#L307

https://github.com/web-standards-ru/weblind.ru/blob/master/src/inner.html#L393

https://github.com/web-standards-ru/weblind.ru/blob/master/src/inner.html#L444

https://github.com/web-standards-ru/weblind.ru/blob/master/src/inner.html#L451

https://github.com/web-standards-ru/weblind.ru/blob/master/src/inner.html#L698

https://github.com/web-standards-ru/weblind.ru/blob/master/src/inner.html#L756

https://github.com/web-standards-ru/weblind.ru/blob/master/src/inner.html#L802

https://github.com/web-standards-ru/weblind.ru/blob/master/src/inner.html#L1109

https://github.com/web-standards-ru/weblind.ru/blob/master/src/inner.html#L1720

**Comment by pepelsbey** [comment]
Это не теги, это атрибуты :) Я бы лучше не убирал инлайновые стили — это повлечёт слишком глубокое внедрение в чужой, не самый простой код. Я бы лучше начал отдельный проект по перевёрстке.
