### ISSUE TITLE
Сделать сайт более доступным

### ISSUE THREAD

**Issue by tsergeytovarov** [web-standards-ru/weblind.ru#27]
Я не знаю, было ли это специально задумано, но я с ходу не нашёл ни однорй картинки у которой был бы alt. aria-hidden="true" или так далее.

**Comment by tsergeytovarov** [comment]
<img width="735" alt="screen shot 2017-11-14 at 21 19 00" src="https://user-images.githubusercontent.com/3905611/32797030-80e62ce2-c981-11e7-80b0-015d41b82562.png">

**Comment by pepelsbey** [comment]
Слишком общая ишья в духе «давайте решим проблемы». Давайте :) Полезно будет разобрать результаты Lighthouse и поставить задачи по каждому.
