### ISSUE TITLE
Пробел после запятых в списке экспертов

### ISSUE THREAD

**Issue by 102** [web-standards-ru/weblind.ru#35]
В нижней части страницы есть список экспертов из которого, видимо, пропали пробелы после запятых

![image](https://user-images.githubusercontent.com/5839225/33121406-d5d19340-cf9e-11e7-8f43-2d1035f505d4.png)

**Comment by 102** [comment]
Исправлено в 2e212db2f246b8d711c47ee2cd70ad2424aa129f 👍

**Comment by pepelsbey** [comment]
:) всё равно спасибо
