### ISSUE TITLE
Починить слетающий вотчер

### ISSUE THREAD

**Issue by pepelsbey** [web-standards-ru/weblind.ru#37]
Когда несколько раз сохраняешь HTML при запущенном вотчере, то иногда выскакивает белая страница. Примерно на втором-третьем сохранении. Нужно почитать [gulpfile.js](https://github.com/web-standards-ru/weblind.ru/blob/master/gulpfile.js) и разобраться, в каком месте я накосячил.

**Comment by olegbilyk** [comment]
Исправлено в ПР #39 🙂
