### ISSUE TITLE
Ссылка на версию Титаника с аудиодескрипцией ведёт на заблокированное видео

### ISSUE THREAD

**Issue by nikolai-shabalin** [web-standards-ru/weblind.ru#49]
В этом тексте на сайте
>Добавьте для видео аудиодескрипцию с описанием происходящего, как Иван Борщевский адаптировал фильм «Титаник».

ссылка ведёт на ютуб с заблокированным видео.

Предлагаю заменить фильм, например, на этот - https://www.youtube.com/watch?v=OOuX63uuy0o

В целом на ютубе множество фильмов с тифлокомментариями.

**Comment by pepelsbey** [comment]
Ждём пулреквест :) Спасибо.

**Comment by nikolai-shabalin** [comment]
"Иван Васильевич меняет профессию" пойдёт как пример?

**Comment by pepelsbey** [comment]
Да, думаю хороший пример. И вроде бы с правами там всё в порядке.

**Comment by nikolai-shabalin** [comment]
Закрыли в #50
