### ISSUE TITLE
Возможно некорректные значения для атрибутов aria-labelledby и aria-describedby

### ISSUE THREAD

**Issue by 102** [web-standards-ru/weblind.ru#62]
Если верить документации mdn ([aria-labelledby](https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/ARIA_Techniques/Using_the_aria-labelledby_attribute), [aria-describedby](https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/ARIA_Techniques/Using_the_aria-describedby_attribute)), эти атрибуты должны иметь значения `a space-separated list of element IDs`; [в примерах](https://github.com/web-standards-ru/weblind.ru/blob/4067b99400b4f3179f975cd3b9ddbe14e13f6506/src/inner.html#L1071) значения указаны через запятую

**Comment by pepelsbey** [comment]
Вы правы, отправите пулреквест?

**Comment by 102** [comment]
Да, хорошо
