### ISSUE TITLE
Исправить орфографические ошибки

### ISSUE THREAD

**Issue by rshapoval** [web-standards-ru/weblind.ru#69]
На странице weblind.ru/inner.html есть парочка ошибок.

![download](https://user-images.githubusercontent.com/59846705/116747075-1132ce00-aa06-11eb-8941-e8347f14c867.png)
![download (1)](https://user-images.githubusercontent.com/59846705/116747100-17c14580-aa06-11eb-88d8-411997284e83.png)

**Comment by pepelsbey** [comment]
Поможете с пулреквестом?
